{ config, lib, pkgs, modulesPath, ... }:

{
  # Auto-generated by nixos-generate-config, customized for dual-LUKS setup
  # System has 2 NVMe drives with LUKS encryption
  # Using LABEL-based device references for portability

  boot.initrd.luks.devices = {
    # Root filesystem (nvme1n1 - data drive)
    "root" = {
      device = "LABEL=luks-root";
      allowDiscards = true;
    };
    # Secondary drive for data (nvme0n1)
    "data" = {
      device = "LABEL=luks-data";
      allowDiscards = true;
    };
  };

  fileSystems."/" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = [ "subvol=@" "compress=zstd" "noatime" ];
  };

  fileSystems."/boot" = {
    device = "LABEL=boot";
    fsType = "vfat";
    neededForBoot = true;
  };

  fileSystems."/home" = {
    device = "/dev/mapper/data";
    fsType = "btrfs";
    options = [ "subvol=@home" "compress=zstd" "noatime" ];
    neededForBoot = false;
  };

  fileSystems."/var/log" = {
    device = "/dev/mapper/data";
    fsType = "btrfs";
    options = [ "subvol=@log" "compress=zstd" "noatime" ];
    neededForBoot = true;
  };

  fileSystems."/var/cache" = {
    device = "/dev/mapper/data";
    fsType = "btrfs";
    options = [ "subvol=@cache" "compress=zstd" "noatime" ];
    neededForBoot = false;
  };

  fileSystems."/var/tmp" = {
    device = "/dev/mapper/data";
    fsType = "btrfs";
    options = [ "subvol=@tmp" "compress=zstd" "noatime" ];
    neededForBoot = false;
  };

  fileSystems."/root" = {
    device = "/dev/mapper/data";
    fsType = "btrfs";
    options = [ "subvol=@root" "compress=zstd" "noatime" ];
    neededForBoot = false;
  };

  fileSystems."/srv" = {
    device = "/dev/mapper/data";
    fsType = "btrfs";
    options = [ "subvol=@srv" "compress=zstd" "noatime" ];
    neededForBoot = false;
  };

  # Use zram instead of traditional swap
  swapDevices = [];
  zramSwap.enable = true;

  # AMD CPU microcode
  hardware.cpu.amd.updateMicrocode = true;
}